

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="ctl00_Head1"><title>
	Türkiye Futbol Federasyonu
</title><link href="../../App_Themes/MainTheme/Common/AdminStyle.css" type="text/css" rel="stylesheet" /><link href="../../App_Themes/MainTheme/Common/FYSStyle.css" type="text/css" rel="stylesheet" /><link href="../../App_Themes/MainTheme/JQuery/jquery-ui.css" type="text/css" rel="stylesheet" /><link href="../../App_Themes/MainTheme/RadControls/Menu/Scripts/4_1_3/menu.css" type="text/css" rel="stylesheet" /><link href="../../App_Themes/MainTheme/RadControls/Menu/Skins/Outlook/styles.css" type="text/css" rel="stylesheet" /><link href="../../App_Themes/MainTheme/RadControls/TreeView/Skins/TFF/Style.css" type="text/css" rel="stylesheet" /><link href="../../App_Themes/MainTheme/RadControls/TreeView/Skins/TFFAnket/Style.css" type="text/css" rel="stylesheet" /><script type='text/javascript' src='/WebResource.axd?d=QU8S7sEHZxuZrHnkTU76vAkso9-3kjLhm_CGFC76ptdKW4B0K1ihVOKTW4XKrSXl61vsrLTxiItH4ElVg5Ah1crJ8qU0qp3lw5FPdna2-Fzai32werR-6Q-FvsVHvkNpUr52ftWqUgn94pfEf2C9WTZ3NhQ1&amp;t=637473684685480830'></script><script type='text/javascript' src='/WebResource.axd?d=ebp5bCEsKKrnt4oc7n5TtZwxYMJHEJ1Uunuw03TUDS5F6l3GTw-WpARwxd-EFas3wJbOBK88Yud3eFf45D6b7PD8FV0EVStAuMhyavifYPMBmTPBEvn9dh20cXgtVgnGb2_F5g2&amp;t=637473684685480830'></script></head>
<body>
    <link href="video-js.min.css" rel="stylesheet" />
    <link href="video-js-resolutions.css" rel="stylesheet" />

    
    <script src="../../script/jquery-1.12.4.js" video.js></script>
    
    <script src="../../script/jquery-migrate-1.4.1.js"></script>
    
        


    <script type="text/javascript" src="video.dev.js"></script>

    <script type="text/javascript" src="video-js-resolutions.js?20241206"></script>

    <script type="text/javascript" src="player.js?20241206"></script>

    <link href="css/AutoCompleteStyleSheet.css" rel="stylesheet" type="text/css" />


    
    
    <script type="text/javascript" src="../../script/jquery-ui.js"></script>
    
    
    <style type="text/css">
        body {
            background-color: #292929;
            font-family: Calibri, Tahoma, Verdana;
            color: White;
            font-size: 16px;
        }

        a:link {
            color: white;
            text-decoration: none;
        }

        a:hover {
            color: white;
            text-decoration: underline;
        }

        a:visited {
            color: white;
            text-decoration: none;
        }

        .inputs {
            font-family: Calibri, Tahoma, Verdana;
            font-size: 16px;
        }

        input {
            font-family: Calibri, Tahoma, Verdana;
            font-size: 16px;
        }

        select {
            font-family: Calibri, Tahoma, Verdana;
            font-size: 16px
        }

        table {
            font-family: Calibri, Tahoma, Verdana;
            font-size: 16px;
        }

        .scoutLinkButton {
            white-space: nowrap;
            width: 154px;
            height: 33px;
            border: 0;
            font-size: 14px;
            color: #d9d9d9;
            text-align: center;
            background-image: url(Image/button3.png);
            background-repeat: no-repeat;
            background-color: transparent
        }

        .scoutLinkButtonXSmall {
            white-space: nowrap;
            width: 60px;
            height: 33px;
            border: 0;
            font-size: 14px;
            color: #d9d9d9;
            text-align: center;
            background-image: url(Image/button3XS.png);
            background-repeat: no-repeat;
            background-color: transparent
        }

        .scoutLinkButtonSmall {
            white-space: nowrap;
            width: 120px;
            height: 33px;
            border: 0;
            font-size: 14px;
            color: #d9d9d9;
            text-align: center;
            background-image: url(Image/button3S.png);
            background-repeat: no-repeat;
            background-color: transparent
        }

        .scoutLinkButtonLong {
            white-space: nowrap;
            width: 220px;
            height: 33px;
            border: 0;
            font-size: 14px;
            color: #d9d9d9;
            text-align: center;
            background-image: url(Image/button3L.png);
            background-repeat: no-repeat;
            background-color: transparent
        }

        .scoutLinkButtonXLong {
            white-space: nowrap;
            width: 300px;
            height: 33px;
            border: 0;
            font-size: 14px;
            color: #d9d9d9;
            text-align: center;
            background-image: url(Image/button3XL.png);
            background-repeat: no-repeat;
            background-color: transparent
        }

        .scoutLinkButtonBig {
            white-space: nowrap;
            width: 154px;
            height: 33px;
            border: 0;
            font-size: 14px;
            font-weight: bold;
            text-align: center;
            background-image: url(Image/button2.png);
            background-repeat: no-repeat;
            background-color: transparent
        }
    </style>
    <script type="text/javascript">
        function autocompleteJSONParseCode(data) {
            var rows = new Array();
            var arr = data.toString().split("\n");
            for (var i = 0, dataLength = arr.length; i < dataLength; i++) {
                 var rowData = arr[i].toString().split("|");
                rows[i] = {
                    value: rowData[0],
                    label: rowData[0],
                    futbolcuID: rowData[1],
                    id :rowData[1]
                };
            }
            return rows;
        }

        function clik_lblUserName() {
            var btn = document.getElementById('ctl00_lblUserName'); 
            btn.click();
        }
    </script>
    <form name="aspnetForm" method="post" action="./MilliTakimlar.aspx" onkeypress="javascript:return WebForm_FireDefaultButton(event, 'ctl00_btnAra')" id="aspnetForm">
<div>
<input type="hidden" name="DialogResultCommand" id="DialogResultCommand" value="" />
<input type="hidden" name="DialogResultParameter" id="DialogResultParameter" value="" />
<input type="hidden" name="DialogResultIsReceived" id="DialogResultIsReceived" value="0" />
<input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="" />
<input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKMTg5NzEwMzU2MQ9kFgJmDw8WAh4PSXNPeXVuY3VHb3JlbWV6aGQWAgIBD2QWCgIBDw8WAh4ISW1hZ2VVcmwFLC9QYWdlcy9TY291dC9JbWFnZS9Vc2VyUGhvdG8vMjU4My5qcGc/dj0yMjAwZGQCAw8PFgIeBFRleHQFCVNUQUogU1RBSmRkAgQPFgIeC18hSXRlbUNvdW50Ah4WPGYPZBYCAgEPDxYKHwIFD01pbGxpIFRha8SxbWxhch4IQ3NzQ2xhc3MFEnNjb3V0TGlua0J1dHRvbkJpZx4NT25DbGllbnRDbGljawVEd2luZG93LmxvY2F0aW9uPScuLi8uLi9QYWdlcy9TY291dC9NaWxsaVRha2ltbGFyLmFzcHgnO3JldHVybiBmYWxzZTseCUZvcmVDb2xvcgkWDdf/HgRfIVNCAgYWBh4Lb25tb3VzZW92ZXIFKnN0eWxlLmNvbG9yPSd3aGl0ZSc7c3R5bGUuY3Vyc29yPSdwb2ludGVyJx4Kb25tb3VzZW91dAVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCceDERlZmF1bHRDb2xvcgUHI2Q3MGQxNmQCAQ9kFgICAQ8PFgofAgUORnV0Ym9sY3VsYXLEsW0fBAUSc2NvdXRMaW5rQnV0dG9uQmlnHwUFRHdpbmRvdy5sb2NhdGlvbj0nLi4vLi4vUGFnZXMvU2NvdXQvRnV0Ym9sY3VsYXJpbS5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCAg9kFgICAQ8PFgofAgUOxLBzdGF0aXN0aWtsZXIfBAUSc2NvdXRMaW5rQnV0dG9uQmlnHwUFRHdpbmRvdy5sb2NhdGlvbj0nLi4vLi4vUGFnZXMvU2NvdXQvSXN0YXRpc3Rpa2xlci5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCAw9kFgICAQ8PFgofAgUSUG9ww7xsZXIgT3l1bmN1bGFyHwQFEnNjb3V0TGlua0J1dHRvbkJpZx8FBUd3aW5kb3cubG9jYXRpb249Jy4uLy4uL1BhZ2VzL1Njb3V0L1BvcHVsZXJPeXVuY3VsYXIuYXNweCc7cmV0dXJuIGZhbHNlOx8GCY+Pj/8fBwIGFgYfCAUqc3R5bGUuY29sb3I9J3doaXRlJztzdHlsZS5jdXJzb3I9J3BvaW50ZXInHwkFRHN0eWxlLmNvbG9yPXRoaXMuZ2V0QXR0cmlidXRlKCdEZWZhdWx0Q29sb3InKTtzdHlsZS5jdXJzb3I9J2RlZmF1bHQnHwoFByM4ZjhmOGZkAgQPZBYCAgEPDxYKHwIFCUt1bMO8cGxlch8EBRJzY291dExpbmtCdXR0b25CaWcfBQU9d2luZG93LmxvY2F0aW9uPScuLi8uLi9QYWdlcy9TY291dC9MaWdsZXIuYXNweCc7cmV0dXJuIGZhbHNlOx8GCY+Pj/8fBwIGFgYfCAUqc3R5bGUuY29sb3I9J3doaXRlJztzdHlsZS5jdXJzb3I9J3BvaW50ZXInHwkFRHN0eWxlLmNvbG9yPXRoaXMuZ2V0QXR0cmlidXRlKCdEZWZhdWx0Q29sb3InKTtzdHlsZS5jdXJzb3I9J2RlZmF1bHQnHwoFByM4ZjhmOGZkAgUPZBYCAgEPDxYKHwIFCEthcm1hbGFyHwQFEnNjb3V0TGlua0J1dHRvbkJpZx8FBT93aW5kb3cubG9jYXRpb249Jy4uLy4uL1BhZ2VzL1Njb3V0L0thcm1hbGFyLmFzcHgnO3JldHVybiBmYWxzZTsfBgmPj4//HwcCBhYGHwgFKnN0eWxlLmNvbG9yPSd3aGl0ZSc7c3R5bGUuY3Vyc29yPSdwb2ludGVyJx8JBURzdHlsZS5jb2xvcj10aGlzLmdldEF0dHJpYnV0ZSgnRGVmYXVsdENvbG9yJyk7c3R5bGUuY3Vyc29yPSdkZWZhdWx0Jx8KBQcjOGY4ZjhmZAIGD2QWAgIBDw8WCh8CBQhSYWtpcGxlch8EBRJzY291dExpbmtCdXR0b25CaWcfBQU/d2luZG93LmxvY2F0aW9uPScuLi8uLi9QYWdlcy9TY291dC9SYWtpcGxlci5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCBw9kFgICAQ8PFgofAgUZQW50cm9wb21ldHJpayDDlmzDp8O8bWxlch8EBRJzY291dExpbmtCdXR0b25CaWcfBQU/d2luZG93LmxvY2F0aW9uPScuLi8uLi9QYWdlcy9TY291dC9PbGN1bWxlci5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCCA9kFgICAQ8PFgofAgURT3l1bmN1IFJhcG9ybGFyxLEfBAUSc2NvdXRMaW5rQnV0dG9uQmlnHwUFP3dpbmRvdy5sb2NhdGlvbj0nLi4vLi4vUGFnZXMvU2NvdXQvUmFwb3JsYXIuYXNweCc7cmV0dXJuIGZhbHNlOx8GCY+Pj/8fBwIGFgYfCAUqc3R5bGUuY29sb3I9J3doaXRlJztzdHlsZS5jdXJzb3I9J3BvaW50ZXInHwkFRHN0eWxlLmNvbG9yPXRoaXMuZ2V0QXR0cmlidXRlKCdEZWZhdWx0Q29sb3InKTtzdHlsZS5jdXJzb3I9J2RlZmF1bHQnHwoFByM4ZjhmOGZkAgkPZBYCAgEPDxYKHwIFEUTDvG55YSBLdXBhc8SxIDI2HwQFEnNjb3V0TGlua0J1dHRvbkJpZx8FBTt3aW5kb3cubG9jYXRpb249Jy4uLy4uL1BhZ2VzL1Njb3V0L1djMjYuYXNweCc7cmV0dXJuIGZhbHNlOx8GCY+Pj/8fBwIGFgYfCAUqc3R5bGUuY29sb3I9J3doaXRlJztzdHlsZS5jdXJzb3I9J3BvaW50ZXInHwkFRHN0eWxlLmNvbG9yPXRoaXMuZ2V0QXR0cmlidXRlKCdEZWZhdWx0Q29sb3InKTtzdHlsZS5jdXJzb3I9J2RlZmF1bHQnHwoFByM4ZjhmOGZkAgoPZBYCAgEPDxYKHwIFEEfDvG5jZWwgVmlkZW9sYXIfBAUSc2NvdXRMaW5rQnV0dG9uQmlnHwUFQXdpbmRvdy5sb2NhdGlvbj0nLi4vLi4vUGFnZXMvU2NvdXQvR2VuZWxWaWRlby5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCCw9kFgICAQ8PFgofAgUQU2NvdXQgUHJvZmlsbGVyaR8EBRJzY291dExpbmtCdXR0b25CaWcfBQU/d2luZG93LmxvY2F0aW9uPScuLi8uLi9QYWdlcy9TY291dC9TY291dGxhci5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCDA9kFgICAQ8PFgofAgUTWWV0ZW5layBCYcWfdnVydWxhch8EBRJzY291dExpbmtCdXR0b25CaWcfBQVGd2luZG93LmxvY2F0aW9uPScuLi8uLi9QYWdlcy9TY291dC9SYXBvcmxhcllldGVuZWsuYXNweCc7cmV0dXJuIGZhbHNlOx8GCY+Pj/8fBwIGFgYfCAUqc3R5bGUuY29sb3I9J3doaXRlJztzdHlsZS5jdXJzb3I9J3BvaW50ZXInHwkFRHN0eWxlLmNvbG9yPXRoaXMuZ2V0QXR0cmlidXRlKCdEZWZhdWx0Q29sb3InKTtzdHlsZS5jdXJzb3I9J2RlZmF1bHQnHwoFByM4ZjhmOGZkAg0PZBYCAgEPDxYKHwIFEkRva8O8bWFuIFnDtm5ldGltaR8EBRJzY291dExpbmtCdXR0b25CaWcfBQU6d2luZG93LmxvY2F0aW9uPScuLi8uLi9QYWdlcy9TY291dC9EWVMuYXNweCc7cmV0dXJuIGZhbHNlOx8GCY+Pj/8fBwIGFgYfCAUqc3R5bGUuY29sb3I9J3doaXRlJztzdHlsZS5jdXJzb3I9J3BvaW50ZXInHwkFRHN0eWxlLmNvbG9yPXRoaXMuZ2V0QXR0cmlidXRlKCdEZWZhdWx0Q29sb3InKTtzdHlsZS5jdXJzb3I9J2RlZmF1bHQnHwoFByM4ZjhmOGZkAg4PZBYCAgEPDxYKHwIFBlJlaGJlch8EBRJzY291dExpbmtCdXR0b25CaWcfBQU9d2luZG93LmxvY2F0aW9uPScuLi8uLi9QYWdlcy9TY291dC9SZWhiZXIuYXNweCc7cmV0dXJuIGZhbHNlOx8GCY+Pj/8fBwIGFgYfCAUqc3R5bGUuY29sb3I9J3doaXRlJztzdHlsZS5jdXJzb3I9J3BvaW50ZXInHwkFRHN0eWxlLmNvbG9yPXRoaXMuZ2V0QXR0cmlidXRlKCdEZWZhdWx0Q29sb3InKTtzdHlsZS5jdXJzb3I9J2RlZmF1bHQnHwoFByM4ZjhmOGZkAg8PZBYCAgEPDxYKHwIFDEVzYW1lIFJhcG9ydR8EBRJzY291dExpbmtCdXR0b25CaWcfBQVOd2luZG93LmxvY2F0aW9uPScuLi8uLi9QYWdlcy9TY291dC9PeXVuY3VudW5PeW5hZGlnaU1hY2xhci5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCEA9kFgICAQ8PFgofAgUITWVzYWpsYXIfBAUSc2NvdXRMaW5rQnV0dG9uQmlnHwUFP3dpbmRvdy5sb2NhdGlvbj0nLi4vLi4vUGFnZXMvU2NvdXQvTWVzYWpsYXIuYXNweCc7cmV0dXJuIGZhbHNlOx8GCY+Pj/8fBwIGFgYfCAUqc3R5bGUuY29sb3I9J3doaXRlJztzdHlsZS5jdXJzb3I9J3BvaW50ZXInHwkFRHN0eWxlLmNvbG9yPXRoaXMuZ2V0QXR0cmlidXRlKCdEZWZhdWx0Q29sb3InKTtzdHlsZS5jdXJzb3I9J2RlZmF1bHQnHwoFByM4ZjhmOGZkAhEPZBYCAgEPDxYKHwIFE0FudHJlbm1hbiBQbGFubGFyxLEfBAUSc2NvdXRMaW5rQnV0dG9uQmlnHwUFR3dpbmRvdy5sb2NhdGlvbj0nLi4vLi4vUGFnZXMvU2NvdXQvQW50cmVubWFuVGFrdmltaS5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCEg9kFgICAQ8PFgofAgUMQW50cmVubWFubGFyHwQFEnNjb3V0TGlua0J1dHRvbkJpZx8FBUN3aW5kb3cubG9jYXRpb249Jy4uLy4uL1BhZ2VzL1Njb3V0L0FudHJlbm1hbmxhci5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCEw9kFgICAQ8PFgofAgUPS3Vsw7xwIEdlbGnFn2ltHwQFEnNjb3V0TGlua0J1dHRvbkJpZx8FBUZ3aW5kb3cubG9jYXRpb249Jy4uLy4uL1BhZ2VzL1Njb3V0L0t1bHVwT3l1bmN1bGFyaS5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCFA9kFgICAQ8PFgofAgUYR2VsacWfaW0gTGlnaSBSYXBvcmxhcsSxHwQFEnNjb3V0TGlua0J1dHRvbkJpZx8FBUt3aW5kb3cubG9jYXRpb249Jy4uLy4uL1BhZ2VzL1Njb3V0L0dlbGlzaW1MaWdpUmFwb3JsYXJpLmFzcHgnO3JldHVybiBmYWxzZTsfBgmPj4//HwcCBhYGHwgFKnN0eWxlLmNvbG9yPSd3aGl0ZSc7c3R5bGUuY3Vyc29yPSdwb2ludGVyJx8JBURzdHlsZS5jb2xvcj10aGlzLmdldEF0dHJpYnV0ZSgnRGVmYXVsdENvbG9yJyk7c3R5bGUuY3Vyc29yPSdkZWZhdWx0Jx8KBQcjOGY4ZjhmZAIVD2QWAgIBDw8WCh8CBRPFnmlmcmUgRGXEn2nFn3Rpcm1lHwQFEnNjb3V0TGlua0J1dHRvbkJpZx8FBUZ3aW5kb3cubG9jYXRpb249Jy4uLy4uL1BhZ2VzL1Njb3V0L1NpZnJlRGVnaXN0aXJtZS5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCFg9kFgICAQ8PFgofAgUTT3l1bmN1IEXFn2xlxZ90aXJtZR8EBRJzY291dExpbmtCdXR0b25CaWcfBQVLd2luZG93LmxvY2F0aW9uPScuLi8uLi9QYWdlcy9TY291dC9PcHRhT3l1bmN1RXNsZXN0aXJtZS5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCFw9kFgICAQ8PFgofAgUSQW5hbGl6IERlcGFydG1hbsSxHwQFEnNjb3V0TGlua0J1dHRvbkJpZx8FBUd3aW5kb3cubG9jYXRpb249Jy4uLy4uL1BhZ2VzL1Njb3V0L0FuYWxpekRlcGFydG1hbmkuYXNweCc7cmV0dXJuIGZhbHNlOx8GCY+Pj/8fBwIGFgYfCAUqc3R5bGUuY29sb3I9J3doaXRlJztzdHlsZS5jdXJzb3I9J3BvaW50ZXInHwkFRHN0eWxlLmNvbG9yPXRoaXMuZ2V0QXR0cmlidXRlKCdEZWZhdWx0Q29sb3InKTtzdHlsZS5jdXJzb3I9J2RlZmF1bHQnHwoFByM4ZjhmOGZkAhgPZBYCAgEPDxYKHwIFE1BlcmZvcm1hbnMgVGVzdGxlcmkfBAUSc2NvdXRMaW5rQnV0dG9uQmlnHwUFPndpbmRvdy5sb2NhdGlvbj0nLi4vLi4vUGFnZXMvU2NvdXQvVGVzdGxlci5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCGQ9kFgICAQ8PFgofAgUOVGVrbmlrIFRlc3RsZXIfBAUSc2NvdXRMaW5rQnV0dG9uQmlnHwUFRHdpbmRvdy5sb2NhdGlvbj0nLi4vLi4vUGFnZXMvU2NvdXQvVGVrbmlrVGVzdGxlci5hc3B4JztyZXR1cm4gZmFsc2U7HwYJj4+P/x8HAgYWBh8IBSpzdHlsZS5jb2xvcj0nd2hpdGUnO3N0eWxlLmN1cnNvcj0ncG9pbnRlcicfCQVEc3R5bGUuY29sb3I9dGhpcy5nZXRBdHRyaWJ1dGUoJ0RlZmF1bHRDb2xvcicpO3N0eWxlLmN1cnNvcj0nZGVmYXVsdCcfCgUHIzhmOGY4ZmQCGg9kFgICAQ8PFgofAgUMU2FrYXRsxLFrbGFyHwQFEnNjb3V0TGlua0J1dHRvbkJpZx8FBUJ3aW5kb3cubG9jYXRpb249Jy4uLy4uL1BhZ2VzL1Njb3V0L1Nha2F0bGlrbGFyLmFzcHgnO3JldHVybiBmYWxzZTsfBgmPj4//HwcCBhYGHwgFKnN0eWxlLmNvbG9yPSd3aGl0ZSc7c3R5bGUuY3Vyc29yPSdwb2ludGVyJx8JBURzdHlsZS5jb2xvcj10aGlzLmdldEF0dHJpYnV0ZSgnRGVmYXVsdENvbG9yJyk7c3R5bGUuY3Vyc29yPSdkZWZhdWx0Jx8KBQcjOGY4ZjhmZAIbD2QWAgIBDw8WCh8CBQ9NYcOnIFJhcG9ybGFyxLEfBAUSc2NvdXRMaW5rQnV0dG9uQmlnHwUFQ3dpbmRvdy5sb2NhdGlvbj0nLi4vLi4vUGFnZXMvU2NvdXQvTWFjUmFwb3JsYXJpLmFzcHgnO3JldHVybiBmYWxzZTsfBgmPj4//HwcCBhYGHwgFKnN0eWxlLmNvbG9yPSd3aGl0ZSc7c3R5bGUuY3Vyc29yPSdwb2ludGVyJx8JBURzdHlsZS5jb2xvcj10aGlzLmdldEF0dHJpYnV0ZSgnRGVmYXVsdENvbG9yJyk7c3R5bGUuY3Vyc29yPSdkZWZhdWx0Jx8KBQcjOGY4ZjhmZAIcD2QWAgIBDw8WCh8CBQ/EsHpsZXlpY2kgQXRhbWEfBAUSc2NvdXRMaW5rQnV0dG9uQmlnHwUFP3dpbmRvdy5sb2NhdGlvbj0nLi4vLi4vUGFnZXMvU2NvdXQvTWFjQXRhbWEuYXNweCc7cmV0dXJuIGZhbHNlOx8GCY+Pj/8fBwIGFgYfCAUqc3R5bGUuY29sb3I9J3doaXRlJztzdHlsZS5jdXJzb3I9J3BvaW50ZXInHwkFRHN0eWxlLmNvbG9yPXRoaXMuZ2V0QXR0cmlidXRlKCdEZWZhdWx0Q29sb3InKTtzdHlsZS5jdXJzb3I9J2RlZmF1bHQnHwoFByM4ZjhmOGZkAh0PZBYCAgEPDxYKHwIFFUt1bGxhbsSxY8SxIFnDtm5ldGltaR8EBRJzY291dExpbmtCdXR0b25CaWcfBQVJd2luZG93LmxvY2F0aW9uPScuLi8uLi9QYWdlcy9TY291dC9LdWxsYW5pY2lTb3JndWxhbWEuYXNweCc7cmV0dXJuIGZhbHNlOx8GCY+Pj/8fBwIGFgYfCAUqc3R5bGUuY29sb3I9J3doaXRlJztzdHlsZS5jdXJzb3I9J3BvaW50ZXInHwkFRHN0eWxlLmNvbG9yPXRoaXMuZ2V0QXR0cmlidXRlKCdEZWZhdWx0Q29sb3InKTtzdHlsZS5jdXJzb3I9J2RlZmF1bHQnHwoFByM4ZjhmOGZkAgYPFgIeCWlubmVyaHRtbAWSASZuYnNwOyZuYnNwOyZuYnNwOzxhIGhyZWY9Ik1pbGxpVGFraW1sYXIuYXNweCI+Jm5ic3A7TWlsbGkgVGFrxLFtbGFyJm5ic3A7PC9hPjxzcGFuIHN0eWxlPSJjb2xvcjojZDcwZDE2O2ZvbnQtd2VpZ2h0OmJvbGQiPiZuYnNwOyZndDsmbmJzcDs8L3NwYW4+ZAIHD2QWAgIBDxYCHwsFpJUBPHRhYmxlIGNlbGxwYWRkaW5nPSIxMCIgY2VsbHNwYWNpbmc9IjEwIj48dHI+PHRkIHN0eWxlPSJib3JkZXI6MXB4IHNvbGlkICM0MjQyNDI7dmVydGljYWwtYWxpZ246dG9wIj48dGFibGUgc3R5bGU9IndpZHRoOjEwMCUiPjx0cj48dGQgb25tb3VzZW92ZXI9InN0eWxlLmN1cnNvcj0ncG9pbnRlciciIG9ubW91c2VvdXQ9InN0eWxlLmN1cnNvcj0nZGVmYXVsdCciIG9uY2xpY2s9IndpbmRvdy5sb2NhdGlvbi5ocmVmPSdNaWxsaVRha2ltbGFyQmlsZ2kuYXNweD9TY291dEt1bHVwSUQ9ajBHcmlWMjdBZ2E4TEJaUFRWZkh1a1NueVJ5YWdDenVEcnRydmh6MTV2OCUzZCZUYWtpbVRpcEtvZHU9REglMmZWVEtHd1ltNTVRcm5DZnZmanFiRk5rUmVtVVBvRVUlMmI5VVJLbnh4c1ElM2QnIj48dGFibGUgY2VsbHBhZGRpbmc9IjAiIGNlbGxzcGFjaW5nPSIwIiBhbGlnbj0iY2VudGVyIj48dHI+PHRkIHN0eWxlPSJ3aWR0aDo5MHB4O2hlaWdodDoxMDBweDt0ZXh0LWFsaWduOmNlbnRlcjtiYWNrZ3JvdW5kLWltYWdlOnVybChJbWFnZS93aGl0ZV9iZy5wbmcpO2JhY2tncm91bmQtcmVwZWF0Om5vLXJlcGVhdDtiYWNrZ3JvdW5kLXBvc2l0aW9uOmNlbnRlciI+PGltZyBib3JkZXI9IjAiIHNyYz0iSW1hZ2UvdGZmNzUucG5nIi8+PC90ZD48L3RyPjx0cj48dGQgc3R5bGU9InRleHQtYWxpZ246Y2VudGVyO3dpZHRoOjkwcHg7b3ZlcmZsb3c6aGlkZGVuO2Rpc3BsYXk6YmxvY2s7IiBvbm1vdXNlb3Zlcj0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0ndW5kZXJsaW5lJyIgb25tb3VzZW91dD0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0nJyI+QSBNaWxsaTwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PHRkIHN0eWxlPSJib3JkZXI6MXB4IHNvbGlkICM0MjQyNDI7dmVydGljYWwtYWxpZ246dG9wIj48dGFibGUgc3R5bGU9IndpZHRoOjEwMCUiPjx0cj48dGQgb25tb3VzZW92ZXI9InN0eWxlLmN1cnNvcj0ncG9pbnRlciciIG9ubW91c2VvdXQ9InN0eWxlLmN1cnNvcj0nZGVmYXVsdCciIG9uY2xpY2s9IndpbmRvdy5sb2NhdGlvbi5ocmVmPSdNaWxsaVRha2ltbGFyQmlsZ2kuYXNweD9TY291dEt1bHVwSUQ9OGdUT292VlpuMGNEdE9Ob0F2RmdRNklBNDd1NlloUGQ4c1pIVldudTJUVSUzZCZUYWtpbVRpcEtvZHU9VyUyZnBFQWdsV2d6cVh2T3RRRklUaG0lMmZFJTJiZ3lpUHdUNSUyZkNwdEI5N2VGVnkwJTNkJyI+PHRhYmxlIGNlbGxwYWRkaW5nPSIwIiBjZWxsc3BhY2luZz0iMCIgYWxpZ249ImNlbnRlciI+PHRyPjx0ZCBzdHlsZT0id2lkdGg6OTBweDtoZWlnaHQ6MTAwcHg7dGV4dC1hbGlnbjpjZW50ZXI7YmFja2dyb3VuZC1pbWFnZTp1cmwoSW1hZ2Uvd2hpdGVfYmcucG5nKTtiYWNrZ3JvdW5kLXJlcGVhdDpuby1yZXBlYXQ7YmFja2dyb3VuZC1wb3NpdGlvbjpjZW50ZXIiPjxpbWcgYm9yZGVyPSIwIiBzcmM9IkltYWdlL3RmZjc1LnBuZyIvPjwvdGQ+PC90cj48dHI+PHRkIHN0eWxlPSJ0ZXh0LWFsaWduOmNlbnRlcjt3aWR0aDo5MHB4O292ZXJmbG93OmhpZGRlbjtkaXNwbGF5OmJsb2NrOyIgb25tb3VzZW92ZXI9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249J3VuZGVybGluZSciIG9ubW91c2VvdXQ9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249JyciPkEyIE1pbGxpPC90ZD48L3RyPjwvdGFibGU+PC90ZD48L3RyPjwvdGFibGU+PC90ZD48dGQgc3R5bGU9ImJvcmRlcjoxcHggc29saWQgIzQyNDI0Mjt2ZXJ0aWNhbC1hbGlnbjp0b3AiPjx0YWJsZSBzdHlsZT0id2lkdGg6MTAwJSI+PHRyPjx0ZCBvbm1vdXNlb3Zlcj0ic3R5bGUuY3Vyc29yPSdwb2ludGVyJyIgb25tb3VzZW91dD0ic3R5bGUuY3Vyc29yPSdkZWZhdWx0JyIgb25jbGljaz0id2luZG93LmxvY2F0aW9uLmhyZWY9J01pbGxpVGFraW1sYXJCaWxnaS5hc3B4P1Njb3V0S3VsdXBJRD10ZSUyYjl3djdKVVlLUHVJYiUyZkg5Z2haQ0lHdnZXQkNvN0ZQJTJmMDZ1NmZiSXpnJTNkJlRha2ltVGlwS29kdT0lMmZ5RFd6Vm5JaSUyZnpxSUVKdGJqWUpxRm8yWmUlMmJLQ3FJcm9qbkhuamVqeWlFJTNkJyI+PHRhYmxlIGNlbGxwYWRkaW5nPSIwIiBjZWxsc3BhY2luZz0iMCIgYWxpZ249ImNlbnRlciI+PHRyPjx0ZCBzdHlsZT0id2lkdGg6OTBweDtoZWlnaHQ6MTAwcHg7dGV4dC1hbGlnbjpjZW50ZXI7YmFja2dyb3VuZC1pbWFnZTp1cmwoSW1hZ2Uvd2hpdGVfYmcucG5nKTtiYWNrZ3JvdW5kLXJlcGVhdDpuby1yZXBlYXQ7YmFja2dyb3VuZC1wb3NpdGlvbjpjZW50ZXIiPjxpbWcgYm9yZGVyPSIwIiBzcmM9IkltYWdlL3RmZjc1LnBuZyIvPjwvdGQ+PC90cj48dHI+PHRkIHN0eWxlPSJ0ZXh0LWFsaWduOmNlbnRlcjt3aWR0aDo5MHB4O292ZXJmbG93OmhpZGRlbjtkaXNwbGF5OmJsb2NrOyIgb25tb3VzZW92ZXI9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249J3VuZGVybGluZSciIG9ubW91c2VvdXQ9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249JyciPlUyMSBNaWxsaTwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PHRkIHN0eWxlPSJib3JkZXI6MXB4IHNvbGlkICM0MjQyNDI7dmVydGljYWwtYWxpZ246dG9wIj48dGFibGUgc3R5bGU9IndpZHRoOjEwMCUiPjx0cj48dGQgb25tb3VzZW92ZXI9InN0eWxlLmN1cnNvcj0ncG9pbnRlciciIG9ubW91c2VvdXQ9InN0eWxlLmN1cnNvcj0nZGVmYXVsdCciIG9uY2xpY2s9IndpbmRvdy5sb2NhdGlvbi5ocmVmPSdNaWxsaVRha2ltbGFyQmlsZ2kuYXNweD9TY291dEt1bHVwSUQ9RGJPUTZKRTFtJTJmekhLU3NFZ2s1UU5WTzZJdk9OV2pmazA3SjA1N3hENnBrJTNkJlRha2ltVGlwS29kdT1tems2OHFHdVFUNno4OVdxUUtRU2Y5TjlCZG1UZWtRcEdQRzJlMCUyZlg0eVUlM2QnIj48dGFibGUgY2VsbHBhZGRpbmc9IjAiIGNlbGxzcGFjaW5nPSIwIiBhbGlnbj0iY2VudGVyIj48dHI+PHRkIHN0eWxlPSJ3aWR0aDo5MHB4O2hlaWdodDoxMDBweDt0ZXh0LWFsaWduOmNlbnRlcjtiYWNrZ3JvdW5kLWltYWdlOnVybChJbWFnZS93aGl0ZV9iZy5wbmcpO2JhY2tncm91bmQtcmVwZWF0Om5vLXJlcGVhdDtiYWNrZ3JvdW5kLXBvc2l0aW9uOmNlbnRlciI+PGltZyBib3JkZXI9IjAiIHNyYz0iSW1hZ2UvdGZmNzUucG5nIi8+PC90ZD48L3RyPjx0cj48dGQgc3R5bGU9InRleHQtYWxpZ246Y2VudGVyO3dpZHRoOjkwcHg7b3ZlcmZsb3c6aGlkZGVuO2Rpc3BsYXk6YmxvY2s7IiBvbm1vdXNlb3Zlcj0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0ndW5kZXJsaW5lJyIgb25tb3VzZW91dD0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0nJyI+VTIwIE1pbGxpPC90ZD48L3RyPjwvdGFibGU+PC90ZD48L3RyPjwvdGFibGU+PC90ZD48dGQgc3R5bGU9ImJvcmRlcjoxcHggc29saWQgIzQyNDI0Mjt2ZXJ0aWNhbC1hbGlnbjp0b3AiPjx0YWJsZSBzdHlsZT0id2lkdGg6MTAwJSI+PHRyPjx0ZCBvbm1vdXNlb3Zlcj0ic3R5bGUuY3Vyc29yPSdwb2ludGVyJyIgb25tb3VzZW91dD0ic3R5bGUuY3Vyc29yPSdkZWZhdWx0JyIgb25jbGljaz0id2luZG93LmxvY2F0aW9uLmhyZWY9J01pbGxpVGFraW1sYXJCaWxnaS5hc3B4P1Njb3V0S3VsdXBJRD1XanlEbm51WlBldGhBJTJmJTJiS2xMMVU1ZEJ6dGtya0Fub2JoU3lod2FOdFp5ZyUzZCZUYWtpbVRpcEtvZHU9YyUyZkNpbmVzU2x6M3F4NVZFdldxZTM4TGxUdiUyZllBcVhZckpsSEMlMmJmZWlUayUzZCciPjx0YWJsZSBjZWxscGFkZGluZz0iMCIgY2VsbHNwYWNpbmc9IjAiIGFsaWduPSJjZW50ZXIiPjx0cj48dGQgc3R5bGU9IndpZHRoOjkwcHg7aGVpZ2h0OjEwMHB4O3RleHQtYWxpZ246Y2VudGVyO2JhY2tncm91bmQtaW1hZ2U6dXJsKEltYWdlL3doaXRlX2JnLnBuZyk7YmFja2dyb3VuZC1yZXBlYXQ6bm8tcmVwZWF0O2JhY2tncm91bmQtcG9zaXRpb246Y2VudGVyIj48aW1nIGJvcmRlcj0iMCIgc3JjPSJJbWFnZS90ZmY3NS5wbmciLz48L3RkPjwvdHI+PHRyPjx0ZCBzdHlsZT0idGV4dC1hbGlnbjpjZW50ZXI7d2lkdGg6OTBweDtvdmVyZmxvdzpoaWRkZW47ZGlzcGxheTpibG9jazsiIG9ubW91c2VvdmVyPSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPSd1bmRlcmxpbmUnIiBvbm1vdXNlb3V0PSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPScnIj5VMTkgTWlsbGk8L3RkPjwvdHI+PC90YWJsZT48L3RkPjwvdHI+PC90YWJsZT48L3RkPjx0ZCBzdHlsZT0iYm9yZGVyOjFweCBzb2xpZCAjNDI0MjQyO3ZlcnRpY2FsLWFsaWduOnRvcCI+PHRhYmxlIHN0eWxlPSJ3aWR0aDoxMDAlIj48dHI+PHRkIG9ubW91c2VvdmVyPSJzdHlsZS5jdXJzb3I9J3BvaW50ZXInIiBvbm1vdXNlb3V0PSJzdHlsZS5jdXJzb3I9J2RlZmF1bHQnIiBvbmNsaWNrPSJ3aW5kb3cubG9jYXRpb24uaHJlZj0nTWlsbGlUYWtpbWxhckJpbGdpLmFzcHg/U2NvdXRLdWx1cElEPWFnV0FFMUJmSkJnMTJuZmZmbDNkUlV2cm4wNmI5YWhwUjB6a05xJTJmbTFrayUzZCZUYWtpbVRpcEtvZHU9OVdJbCUyZiUyZjlXM2ZQZXlWTXBaRXQwciUyYk45bEhsMkdFS1FCTEFZcEh4b3FqOCUzZCciPjx0YWJsZSBjZWxscGFkZGluZz0iMCIgY2VsbHNwYWNpbmc9IjAiIGFsaWduPSJjZW50ZXIiPjx0cj48dGQgc3R5bGU9IndpZHRoOjkwcHg7aGVpZ2h0OjEwMHB4O3RleHQtYWxpZ246Y2VudGVyO2JhY2tncm91bmQtaW1hZ2U6dXJsKEltYWdlL3doaXRlX2JnLnBuZyk7YmFja2dyb3VuZC1yZXBlYXQ6bm8tcmVwZWF0O2JhY2tncm91bmQtcG9zaXRpb246Y2VudGVyIj48aW1nIGJvcmRlcj0iMCIgc3JjPSJJbWFnZS90ZmY3NS5wbmciLz48L3RkPjwvdHI+PHRyPjx0ZCBzdHlsZT0idGV4dC1hbGlnbjpjZW50ZXI7d2lkdGg6OTBweDtvdmVyZmxvdzpoaWRkZW47ZGlzcGxheTpibG9jazsiIG9ubW91c2VvdmVyPSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPSd1bmRlcmxpbmUnIiBvbm1vdXNlb3V0PSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPScnIj5VMTggTWlsbGk8L3RkPjwvdHI+PC90YWJsZT48L3RkPjwvdHI+PC90YWJsZT48L3RkPjwvdHI+PHRyPjx0ZCBzdHlsZT0iYm9yZGVyOjFweCBzb2xpZCAjNDI0MjQyO3ZlcnRpY2FsLWFsaWduOnRvcCI+PHRhYmxlIHN0eWxlPSJ3aWR0aDoxMDAlIj48dHI+PHRkIG9ubW91c2VvdmVyPSJzdHlsZS5jdXJzb3I9J3BvaW50ZXInIiBvbm1vdXNlb3V0PSJzdHlsZS5jdXJzb3I9J2RlZmF1bHQnIiBvbmNsaWNrPSJ3aW5kb3cubG9jYXRpb24uaHJlZj0nTWlsbGlUYWtpbWxhckJpbGdpLmFzcHg/U2NvdXRLdWx1cElEPXI3Y1VaJTJiV0NvWGFsSEd1a1pISkM5RmFLUklGNFBpN2tPR1Mzek5hYzZ4USUzZCZUYWtpbVRpcEtvZHU9Mndlc0twMGdxSVFVZDhIdG53a0xzRlU5TW5QYWlKczlGb2IlMmZHR0dRRFA4JTNkJyI+PHRhYmxlIGNlbGxwYWRkaW5nPSIwIiBjZWxsc3BhY2luZz0iMCIgYWxpZ249ImNlbnRlciI+PHRyPjx0ZCBzdHlsZT0id2lkdGg6OTBweDtoZWlnaHQ6MTAwcHg7dGV4dC1hbGlnbjpjZW50ZXI7YmFja2dyb3VuZC1pbWFnZTp1cmwoSW1hZ2Uvd2hpdGVfYmcucG5nKTtiYWNrZ3JvdW5kLXJlcGVhdDpuby1yZXBlYXQ7YmFja2dyb3VuZC1wb3NpdGlvbjpjZW50ZXIiPjxpbWcgYm9yZGVyPSIwIiBzcmM9IkltYWdlL3RmZjc1LnBuZyIvPjwvdGQ+PC90cj48dHI+PHRkIHN0eWxlPSJ0ZXh0LWFsaWduOmNlbnRlcjt3aWR0aDo5MHB4O292ZXJmbG93OmhpZGRlbjtkaXNwbGF5OmJsb2NrOyIgb25tb3VzZW92ZXI9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249J3VuZGVybGluZSciIG9ubW91c2VvdXQ9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249JyciPlUxNyBNaWxsaTwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PHRkIHN0eWxlPSJib3JkZXI6MXB4IHNvbGlkICM0MjQyNDI7dmVydGljYWwtYWxpZ246dG9wIj48dGFibGUgc3R5bGU9IndpZHRoOjEwMCUiPjx0cj48dGQgb25tb3VzZW92ZXI9InN0eWxlLmN1cnNvcj0ncG9pbnRlciciIG9ubW91c2VvdXQ9InN0eWxlLmN1cnNvcj0nZGVmYXVsdCciIG9uY2xpY2s9IndpbmRvdy5sb2NhdGlvbi5ocmVmPSdNaWxsaVRha2ltbGFyQmlsZ2kuYXNweD9TY291dEt1bHVwSUQ9RmNVQmZxQ2JmaiUyYmpWdEg2ZWFhdW5hTDBwZFlaJTJieFZWRkRBOFV6R2xTQ0ElM2QmVGFraW1UaXBLb2R1PU1tbVM4SUg5TDIxeHFkR0s1VHo0QzFBd21IQzZKVmZ0aFRlMU5PdmNCM00lM2QnIj48dGFibGUgY2VsbHBhZGRpbmc9IjAiIGNlbGxzcGFjaW5nPSIwIiBhbGlnbj0iY2VudGVyIj48dHI+PHRkIHN0eWxlPSJ3aWR0aDo5MHB4O2hlaWdodDoxMDBweDt0ZXh0LWFsaWduOmNlbnRlcjtiYWNrZ3JvdW5kLWltYWdlOnVybChJbWFnZS93aGl0ZV9iZy5wbmcpO2JhY2tncm91bmQtcmVwZWF0Om5vLXJlcGVhdDtiYWNrZ3JvdW5kLXBvc2l0aW9uOmNlbnRlciI+PGltZyBib3JkZXI9IjAiIHNyYz0iSW1hZ2UvdGZmNzUucG5nIi8+PC90ZD48L3RyPjx0cj48dGQgc3R5bGU9InRleHQtYWxpZ246Y2VudGVyO3dpZHRoOjkwcHg7b3ZlcmZsb3c6aGlkZGVuO2Rpc3BsYXk6YmxvY2s7IiBvbm1vdXNlb3Zlcj0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0ndW5kZXJsaW5lJyIgb25tb3VzZW91dD0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0nJyI+VTE2IE1pbGxpPC90ZD48L3RyPjwvdGFibGU+PC90ZD48L3RyPjwvdGFibGU+PC90ZD48dGQgc3R5bGU9ImJvcmRlcjoxcHggc29saWQgIzQyNDI0Mjt2ZXJ0aWNhbC1hbGlnbjp0b3AiPjx0YWJsZSBzdHlsZT0id2lkdGg6MTAwJSI+PHRyPjx0ZCBvbm1vdXNlb3Zlcj0ic3R5bGUuY3Vyc29yPSdwb2ludGVyJyIgb25tb3VzZW91dD0ic3R5bGUuY3Vyc29yPSdkZWZhdWx0JyIgb25jbGljaz0id2luZG93LmxvY2F0aW9uLmhyZWY9J01pbGxpVGFraW1sYXJCaWxnaS5hc3B4P1Njb3V0S3VsdXBJRD1scTZDTWZGJTJiMk1uQlhzUXpkN3NFOHFGcGx0bXl4dWp5Q0lqR1V3ZWVwVVElM2QmVGFraW1UaXBLb2R1PTA0ZktoTENMJTJiZFdmdFMlMmI1R0JQQ2FLWlNyTHdEZzI1Y3d5anBSWGJGdjdJJTNkJyI+PHRhYmxlIGNlbGxwYWRkaW5nPSIwIiBjZWxsc3BhY2luZz0iMCIgYWxpZ249ImNlbnRlciI+PHRyPjx0ZCBzdHlsZT0id2lkdGg6OTBweDtoZWlnaHQ6MTAwcHg7dGV4dC1hbGlnbjpjZW50ZXI7YmFja2dyb3VuZC1pbWFnZTp1cmwoSW1hZ2Uvd2hpdGVfYmcucG5nKTtiYWNrZ3JvdW5kLXJlcGVhdDpuby1yZXBlYXQ7YmFja2dyb3VuZC1wb3NpdGlvbjpjZW50ZXIiPjxpbWcgYm9yZGVyPSIwIiBzcmM9IkltYWdlL3RmZjc1LnBuZyIvPjwvdGQ+PC90cj48dHI+PHRkIHN0eWxlPSJ0ZXh0LWFsaWduOmNlbnRlcjt3aWR0aDo5MHB4O292ZXJmbG93OmhpZGRlbjtkaXNwbGF5OmJsb2NrOyIgb25tb3VzZW92ZXI9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249J3VuZGVybGluZSciIG9ubW91c2VvdXQ9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249JyciPlUxNSBNaWxsaTwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PHRkIHN0eWxlPSJib3JkZXI6MXB4IHNvbGlkICM0MjQyNDI7dmVydGljYWwtYWxpZ246dG9wIj48dGFibGUgc3R5bGU9IndpZHRoOjEwMCUiPjx0cj48dGQgb25tb3VzZW92ZXI9InN0eWxlLmN1cnNvcj0ncG9pbnRlciciIG9ubW91c2VvdXQ9InN0eWxlLmN1cnNvcj0nZGVmYXVsdCciIG9uY2xpY2s9IndpbmRvdy5sb2NhdGlvbi5ocmVmPSdNaWxsaVRha2ltbGFyQmlsZ2kuYXNweD9TY291dEt1bHVwSUQ9ZkNSSnowQkklMmZrY080ejd2NzRLbnV0UHZmQyUyZlJIR1J0UGVHdjB6ZzlieEElM2QmVGFraW1UaXBLb2R1PThvbXpoV1JUY2l0V0YlMmZsaTNCalJmJTJmeDlGUSUyZmJJbk1VRHVyJTJmV2FIYjZJUSUzZCciPjx0YWJsZSBjZWxscGFkZGluZz0iMCIgY2VsbHNwYWNpbmc9IjAiIGFsaWduPSJjZW50ZXIiPjx0cj48dGQgc3R5bGU9IndpZHRoOjkwcHg7aGVpZ2h0OjEwMHB4O3RleHQtYWxpZ246Y2VudGVyO2JhY2tncm91bmQtaW1hZ2U6dXJsKEltYWdlL3doaXRlX2JnLnBuZyk7YmFja2dyb3VuZC1yZXBlYXQ6bm8tcmVwZWF0O2JhY2tncm91bmQtcG9zaXRpb246Y2VudGVyIj48aW1nIGJvcmRlcj0iMCIgc3JjPSJJbWFnZS90ZmY3NS5wbmciLz48L3RkPjwvdHI+PHRyPjx0ZCBzdHlsZT0idGV4dC1hbGlnbjpjZW50ZXI7d2lkdGg6OTBweDtvdmVyZmxvdzpoaWRkZW47ZGlzcGxheTpibG9jazsiIG9ubW91c2VvdmVyPSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPSd1bmRlcmxpbmUnIiBvbm1vdXNlb3V0PSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPScnIj5VMTQgTWlsbGk8L3RkPjwvdHI+PC90YWJsZT48L3RkPjwvdHI+PC90YWJsZT48L3RkPjx0ZCBzdHlsZT0iYm9yZGVyOjFweCBzb2xpZCAjNDI0MjQyO3ZlcnRpY2FsLWFsaWduOnRvcCI+PHRhYmxlIHN0eWxlPSJ3aWR0aDoxMDAlIj48dHI+PHRkIG9ubW91c2VvdmVyPSJzdHlsZS5jdXJzb3I9J3BvaW50ZXInIiBvbm1vdXNlb3V0PSJzdHlsZS5jdXJzb3I9J2RlZmF1bHQnIiBvbmNsaWNrPSJ3aW5kb3cubG9jYXRpb24uaHJlZj0nTWlsbGlUYWtpbWxhckJpbGdpLmFzcHg/U2NvdXRLdWx1cElEPThvbXpoV1JUY2l0V0YlMmZsaTNCalJmJTJmeDlGUSUyZmJJbk1VRHVyJTJmV2FIYjZJUSUzZCZUYWtpbVRpcEtvZHU9JTJmbWhBQkpBbHd4eVVMeXRjbUlKcWhldHZPRFdhS1V5RW04TDlDaUFaUkpBJTNkJyI+PHRhYmxlIGNlbGxwYWRkaW5nPSIwIiBjZWxsc3BhY2luZz0iMCIgYWxpZ249ImNlbnRlciI+PHRyPjx0ZCBzdHlsZT0id2lkdGg6OTBweDtoZWlnaHQ6MTAwcHg7dGV4dC1hbGlnbjpjZW50ZXI7YmFja2dyb3VuZC1pbWFnZTp1cmwoSW1hZ2Uvd2hpdGVfYmcucG5nKTtiYWNrZ3JvdW5kLXJlcGVhdDpuby1yZXBlYXQ7YmFja2dyb3VuZC1wb3NpdGlvbjpjZW50ZXIiPjxpbWcgYm9yZGVyPSIwIiBzcmM9IkltYWdlL3RmZjc1LnBuZyIvPjwvdGQ+PC90cj48dHI+PHRkIHN0eWxlPSJ0ZXh0LWFsaWduOmNlbnRlcjt3aWR0aDo5MHB4O292ZXJmbG93OmhpZGRlbjtkaXNwbGF5OmJsb2NrOyIgb25tb3VzZW92ZXI9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249J3VuZGVybGluZSciIG9ubW91c2VvdXQ9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249JyciPkthZMSxbmxhciBBIE1pbGxpPC90ZD48L3RyPjwvdGFibGU+PC90ZD48L3RyPjwvdGFibGU+PC90ZD48dGQgc3R5bGU9ImJvcmRlcjoxcHggc29saWQgIzQyNDI0Mjt2ZXJ0aWNhbC1hbGlnbjp0b3AiPjx0YWJsZSBzdHlsZT0id2lkdGg6MTAwJSI+PHRyPjx0ZCBvbm1vdXNlb3Zlcj0ic3R5bGUuY3Vyc29yPSdwb2ludGVyJyIgb25tb3VzZW91dD0ic3R5bGUuY3Vyc29yPSdkZWZhdWx0JyIgb25jbGljaz0id2luZG93LmxvY2F0aW9uLmhyZWY9J01pbGxpVGFraW1sYXJCaWxnaS5hc3B4P1Njb3V0S3VsdXBJRD05cmpTTGF6bnlXRG1XSHBaalllMEd2c1h6JTJiams1aVh6MnpwdDZHbVJBS1UlM2QmVGFraW1UaXBLb2R1PVBtVjFoNXY3R2JzajNNN1lYNVlUVmFMdFdkM0JBZ2dqTFhWd2VORnlPSm8lM2QnIj48dGFibGUgY2VsbHBhZGRpbmc9IjAiIGNlbGxzcGFjaW5nPSIwIiBhbGlnbj0iY2VudGVyIj48dHI+PHRkIHN0eWxlPSJ3aWR0aDo5MHB4O2hlaWdodDoxMDBweDt0ZXh0LWFsaWduOmNlbnRlcjtiYWNrZ3JvdW5kLWltYWdlOnVybChJbWFnZS93aGl0ZV9iZy5wbmcpO2JhY2tncm91bmQtcmVwZWF0Om5vLXJlcGVhdDtiYWNrZ3JvdW5kLXBvc2l0aW9uOmNlbnRlciI+PGltZyBib3JkZXI9IjAiIHNyYz0iSW1hZ2UvdGZmNzUucG5nIi8+PC90ZD48L3RyPjx0cj48dGQgc3R5bGU9InRleHQtYWxpZ246Y2VudGVyO3dpZHRoOjkwcHg7b3ZlcmZsb3c6aGlkZGVuO2Rpc3BsYXk6YmxvY2s7IiBvbm1vdXNlb3Zlcj0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0ndW5kZXJsaW5lJyIgb25tb3VzZW91dD0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0nJyI+S2FkxLFubGFyIFUyMyBNaWxsaTwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PC90cj48dHI+PHRkIHN0eWxlPSJib3JkZXI6MXB4IHNvbGlkICM0MjQyNDI7dmVydGljYWwtYWxpZ246dG9wIj48dGFibGUgc3R5bGU9IndpZHRoOjEwMCUiPjx0cj48dGQgb25tb3VzZW92ZXI9InN0eWxlLmN1cnNvcj0ncG9pbnRlciciIG9ubW91c2VvdXQ9InN0eWxlLmN1cnNvcj0nZGVmYXVsdCciIG9uY2xpY2s9IndpbmRvdy5sb2NhdGlvbi5ocmVmPSdNaWxsaVRha2ltbGFyQmlsZ2kuYXNweD9TY291dEt1bHVwSUQ9MDRmS2hMQ0wlMmJkV2Z0UyUyYjVHQlBDYUtaU3JMd0RnMjVjd3lqcFJYYkZ2N0klM2QmVGFraW1UaXBLb2R1PWh3OERVTFdXVXNpN05YcXVnam1HcExEVVhJM3hyRWtuYjNYR0xuR3JFb1UlM2QnIj48dGFibGUgY2VsbHBhZGRpbmc9IjAiIGNlbGxzcGFjaW5nPSIwIiBhbGlnbj0iY2VudGVyIj48dHI+PHRkIHN0eWxlPSJ3aWR0aDo5MHB4O2hlaWdodDoxMDBweDt0ZXh0LWFsaWduOmNlbnRlcjtiYWNrZ3JvdW5kLWltYWdlOnVybChJbWFnZS93aGl0ZV9iZy5wbmcpO2JhY2tncm91bmQtcmVwZWF0Om5vLXJlcGVhdDtiYWNrZ3JvdW5kLXBvc2l0aW9uOmNlbnRlciI+PGltZyBib3JkZXI9IjAiIHNyYz0iSW1hZ2UvdGZmNzUucG5nIi8+PC90ZD48L3RyPjx0cj48dGQgc3R5bGU9InRleHQtYWxpZ246Y2VudGVyO3dpZHRoOjkwcHg7b3ZlcmZsb3c6aGlkZGVuO2Rpc3BsYXk6YmxvY2s7IiBvbm1vdXNlb3Zlcj0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0ndW5kZXJsaW5lJyIgb25tb3VzZW91dD0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0nJyI+S2FkxLFubGFyIFUxOSBNaWxsaTwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PHRkIHN0eWxlPSJib3JkZXI6MXB4IHNvbGlkICM0MjQyNDI7dmVydGljYWwtYWxpZ246dG9wIj48dGFibGUgc3R5bGU9IndpZHRoOjEwMCUiPjx0cj48dGQgb25tb3VzZW92ZXI9InN0eWxlLmN1cnNvcj0ncG9pbnRlciciIG9ubW91c2VvdXQ9InN0eWxlLmN1cnNvcj0nZGVmYXVsdCciIG9uY2xpY2s9IndpbmRvdy5sb2NhdGlvbi5ocmVmPSdNaWxsaVRha2ltbGFyQmlsZ2kuYXNweD9TY291dEt1bHVwSUQ9THVsMTJwajVZUkNLdmpnVTQ0SVUzTU5KbXVzcnliaUVuZGlBSmp6U3FTcyUzZCZUYWtpbVRpcEtvZHU9MVprd2xBdGpobzlZSXhnMyUyYmF4bW1JRmx6aTJhWmslMmJsVXVoWEl6YTMlMmIyWSUzZCciPjx0YWJsZSBjZWxscGFkZGluZz0iMCIgY2VsbHNwYWNpbmc9IjAiIGFsaWduPSJjZW50ZXIiPjx0cj48dGQgc3R5bGU9IndpZHRoOjkwcHg7aGVpZ2h0OjEwMHB4O3RleHQtYWxpZ246Y2VudGVyO2JhY2tncm91bmQtaW1hZ2U6dXJsKEltYWdlL3doaXRlX2JnLnBuZyk7YmFja2dyb3VuZC1yZXBlYXQ6bm8tcmVwZWF0O2JhY2tncm91bmQtcG9zaXRpb246Y2VudGVyIj48aW1nIGJvcmRlcj0iMCIgc3JjPSJJbWFnZS90ZmY3NS5wbmciLz48L3RkPjwvdHI+PHRyPjx0ZCBzdHlsZT0idGV4dC1hbGlnbjpjZW50ZXI7d2lkdGg6OTBweDtvdmVyZmxvdzpoaWRkZW47ZGlzcGxheTpibG9jazsiIG9ubW91c2VvdmVyPSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPSd1bmRlcmxpbmUnIiBvbm1vdXNlb3V0PSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPScnIj5LxLF6bGFyIFUxOCBNaWxsaTwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PHRkIHN0eWxlPSJib3JkZXI6MXB4IHNvbGlkICM0MjQyNDI7dmVydGljYWwtYWxpZ246dG9wIj48dGFibGUgc3R5bGU9IndpZHRoOjEwMCUiPjx0cj48dGQgb25tb3VzZW92ZXI9InN0eWxlLmN1cnNvcj0ncG9pbnRlciciIG9ubW91c2VvdXQ9InN0eWxlLmN1cnNvcj0nZGVmYXVsdCciIG9uY2xpY2s9IndpbmRvdy5sb2NhdGlvbi5ocmVmPSdNaWxsaVRha2ltbGFyQmlsZ2kuYXNweD9TY291dEt1bHVwSUQ9TW1tUzhJSDlMMjF4cWRHSzVUejRDMUF3bUhDNkpWZnRoVGUxTk92Y0IzTSUzZCZUYWtpbVRpcEtvZHU9VGplcXEyZ1cyJTJma05xSjhYeTgwbUJvUXR4Tm0lMmYxYmtvVThhWFdvbHJ6YTQlM2QnIj48dGFibGUgY2VsbHBhZGRpbmc9IjAiIGNlbGxzcGFjaW5nPSIwIiBhbGlnbj0iY2VudGVyIj48dHI+PHRkIHN0eWxlPSJ3aWR0aDo5MHB4O2hlaWdodDoxMDBweDt0ZXh0LWFsaWduOmNlbnRlcjtiYWNrZ3JvdW5kLWltYWdlOnVybChJbWFnZS93aGl0ZV9iZy5wbmcpO2JhY2tncm91bmQtcmVwZWF0Om5vLXJlcGVhdDtiYWNrZ3JvdW5kLXBvc2l0aW9uOmNlbnRlciI+PGltZyBib3JkZXI9IjAiIHNyYz0iSW1hZ2UvdGZmNzUucG5nIi8+PC90ZD48L3RyPjx0cj48dGQgc3R5bGU9InRleHQtYWxpZ246Y2VudGVyO3dpZHRoOjkwcHg7b3ZlcmZsb3c6aGlkZGVuO2Rpc3BsYXk6YmxvY2s7IiBvbm1vdXNlb3Zlcj0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0ndW5kZXJsaW5lJyIgb25tb3VzZW91dD0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0nJyI+S8SxemxhciBVMTcgTWlsbGk8L3RkPjwvdHI+PC90YWJsZT48L3RkPjwvdHI+PC90YWJsZT48L3RkPjx0ZCBzdHlsZT0iYm9yZGVyOjFweCBzb2xpZCAjNDI0MjQyO3ZlcnRpY2FsLWFsaWduOnRvcCI+PHRhYmxlIHN0eWxlPSJ3aWR0aDoxMDAlIj48dHI+PHRkIG9ubW91c2VvdmVyPSJzdHlsZS5jdXJzb3I9J3BvaW50ZXInIiBvbm1vdXNlb3V0PSJzdHlsZS5jdXJzb3I9J2RlZmF1bHQnIiBvbmNsaWNrPSJ3aW5kb3cubG9jYXRpb24uaHJlZj0nTWlsbGlUYWtpbWxhckJpbGdpLmFzcHg/U2NvdXRLdWx1cElEPTJ3ZXNLcDBncUlRVWQ4SHRud2tMc0ZVOU1uUGFpSnM5Rm9iJTJmR0dHUURQOCUzZCZUYWtpbVRpcEtvZHU9RG14SkNSdiUyYmh5YSUyZjdNJTJiN1l6Y3l4ZldibmkxWEdxM2JKNER0d0VtJTJiMDJJJTNkJyI+PHRhYmxlIGNlbGxwYWRkaW5nPSIwIiBjZWxsc3BhY2luZz0iMCIgYWxpZ249ImNlbnRlciI+PHRyPjx0ZCBzdHlsZT0id2lkdGg6OTBweDtoZWlnaHQ6MTAwcHg7dGV4dC1hbGlnbjpjZW50ZXI7YmFja2dyb3VuZC1pbWFnZTp1cmwoSW1hZ2Uvd2hpdGVfYmcucG5nKTtiYWNrZ3JvdW5kLXJlcGVhdDpuby1yZXBlYXQ7YmFja2dyb3VuZC1wb3NpdGlvbjpjZW50ZXIiPjxpbWcgYm9yZGVyPSIwIiBzcmM9IkltYWdlL3RmZjc1LnBuZyIvPjwvdGQ+PC90cj48dHI+PHRkIHN0eWxlPSJ0ZXh0LWFsaWduOmNlbnRlcjt3aWR0aDo5MHB4O292ZXJmbG93OmhpZGRlbjtkaXNwbGF5OmJsb2NrOyIgb25tb3VzZW92ZXI9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249J3VuZGVybGluZSciIG9ubW91c2VvdXQ9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249JyciPkvEsXpsYXIgVTE1IE1pbGxpPC90ZD48L3RyPjwvdGFibGU+PC90ZD48L3RyPjwvdGFibGU+PC90ZD48dGQgc3R5bGU9ImJvcmRlcjoxcHggc29saWQgIzQyNDI0Mjt2ZXJ0aWNhbC1hbGlnbjp0b3AiPjx0YWJsZSBzdHlsZT0id2lkdGg6MTAwJSI+PHRyPjx0ZCBvbm1vdXNlb3Zlcj0ic3R5bGUuY3Vyc29yPSdwb2ludGVyJyIgb25tb3VzZW91dD0ic3R5bGUuY3Vyc29yPSdkZWZhdWx0JyIgb25jbGljaz0id2luZG93LmxvY2F0aW9uLmhyZWY9J01pbGxpVGFraW1sYXJCaWxnaS5hc3B4P1Njb3V0S3VsdXBJRD05V0lsJTJmJTJmOVczZlBleVZNcFpFdDByJTJiTjlsSGwyR0VLUUJMQVlwSHhvcWo4JTNkJlRha2ltVGlwS29kdT1LR1dvOSUyZkc4SnNQN2ZWaE1Qd1FKJTJmWVhISmd6eXhNcExFcndVRUNjdFVxNCUzZCciPjx0YWJsZSBjZWxscGFkZGluZz0iMCIgY2VsbHNwYWNpbmc9IjAiIGFsaWduPSJjZW50ZXIiPjx0cj48dGQgc3R5bGU9IndpZHRoOjkwcHg7aGVpZ2h0OjEwMHB4O3RleHQtYWxpZ246Y2VudGVyO2JhY2tncm91bmQtaW1hZ2U6dXJsKEltYWdlL3doaXRlX2JnLnBuZyk7YmFja2dyb3VuZC1yZXBlYXQ6bm8tcmVwZWF0O2JhY2tncm91bmQtcG9zaXRpb246Y2VudGVyIj48aW1nIGJvcmRlcj0iMCIgc3JjPSJJbWFnZS90ZmY3NS5wbmciLz48L3RkPjwvdHI+PHRyPjx0ZCBzdHlsZT0idGV4dC1hbGlnbjpjZW50ZXI7d2lkdGg6OTBweDtvdmVyZmxvdzpoaWRkZW47ZGlzcGxheTpibG9jazsiIG9ubW91c2VvdmVyPSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPSd1bmRlcmxpbmUnIiBvbm1vdXNlb3V0PSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPScnIj5GdXRzYWwgTWlsbGk8L3RkPjwvdHI+PC90YWJsZT48L3RkPjwvdHI+PC90YWJsZT48L3RkPjx0ZCBzdHlsZT0iYm9yZGVyOjFweCBzb2xpZCAjNDI0MjQyO3ZlcnRpY2FsLWFsaWduOnRvcCI+PHRhYmxlIHN0eWxlPSJ3aWR0aDoxMDAlIj48dHI+PHRkIG9ubW91c2VvdmVyPSJzdHlsZS5jdXJzb3I9J3BvaW50ZXInIiBvbm1vdXNlb3V0PSJzdHlsZS5jdXJzb3I9J2RlZmF1bHQnIiBvbmNsaWNrPSJ3aW5kb3cubG9jYXRpb24uaHJlZj0nTWlsbGlUYWtpbWxhckJpbGdpLmFzcHg/U2NvdXRLdWx1cElEPWMlMmZDaW5lc1NsejNxeDVWRXZXcWUzOExsVHYlMmZZQXFYWXJKbEhDJTJiZmVpVGslM2QmVGFraW1UaXBLb2R1PVA1WTdadWw3THJqQ3ZGeUc4dXNJdWkxYWZJUXQxd0w1amNiT29JTVc2cVElM2QnIj48dGFibGUgY2VsbHBhZGRpbmc9IjAiIGNlbGxzcGFjaW5nPSIwIiBhbGlnbj0iY2VudGVyIj48dHI+PHRkIHN0eWxlPSJ3aWR0aDo5MHB4O2hlaWdodDoxMDBweDt0ZXh0LWFsaWduOmNlbnRlcjtiYWNrZ3JvdW5kLWltYWdlOnVybChJbWFnZS93aGl0ZV9iZy5wbmcpO2JhY2tncm91bmQtcmVwZWF0Om5vLXJlcGVhdDtiYWNrZ3JvdW5kLXBvc2l0aW9uOmNlbnRlciI+PGltZyBib3JkZXI9IjAiIHNyYz0iSW1hZ2UvdGZmNzUucG5nIi8+PC90ZD48L3RyPjx0cj48dGQgc3R5bGU9InRleHQtYWxpZ246Y2VudGVyO3dpZHRoOjkwcHg7b3ZlcmZsb3c6aGlkZGVuO2Rpc3BsYXk6YmxvY2s7IiBvbm1vdXNlb3Zlcj0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0ndW5kZXJsaW5lJyIgb25tb3VzZW91dD0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0nJyI+UGxhaiBNaWxsaTwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PC90cj48L3RhYmxlPjwvdGQ+PC90cj48dHI+PHRkIHN0eWxlPSJib3JkZXI6MXB4IHNvbGlkICM0MjQyNDI7dmVydGljYWwtYWxpZ246dG9wIj48dGFibGUgc3R5bGU9IndpZHRoOjEwMCUiPjx0cj48dGQgb25tb3VzZW92ZXI9InN0eWxlLmN1cnNvcj0ncG9pbnRlciciIG9ubW91c2VvdXQ9InN0eWxlLmN1cnNvcj0nZGVmYXVsdCciIG9uY2xpY2s9IndpbmRvdy5sb2NhdGlvbi5ocmVmPSdNaWxsaVRha2ltbGFyQmlsZ2kuYXNweD9TY291dEt1bHVwSUQ9WGJLQnZqTzBsRTVWenp0N0dET1BZejFNN3J2UzFFT1ExSks0VHpiaFB6YyUzZCZUYWtpbVRpcEtvZHU9NjI5ZHUlMmZmTXozQzhrJTJiT1A1ckRwNEd6cVhBVkF4Y1lDR0hybEpWcmRTRnMlM2QnIj48dGFibGUgY2VsbHBhZGRpbmc9IjAiIGNlbGxzcGFjaW5nPSIwIiBhbGlnbj0iY2VudGVyIj48dHI+PHRkIHN0eWxlPSJ3aWR0aDo5MHB4O2hlaWdodDoxMDBweDt0ZXh0LWFsaWduOmNlbnRlcjtiYWNrZ3JvdW5kLWltYWdlOnVybChJbWFnZS93aGl0ZV9iZy5wbmcpO2JhY2tncm91bmQtcmVwZWF0Om5vLXJlcGVhdDtiYWNrZ3JvdW5kLXBvc2l0aW9uOmNlbnRlciI+PGltZyBib3JkZXI9IjAiIHNyYz0iSW1hZ2UvdGZmNzUucG5nIi8+PC90ZD48L3RyPjx0cj48dGQgc3R5bGU9InRleHQtYWxpZ246Y2VudGVyO3dpZHRoOjkwcHg7b3ZlcmZsb3c6aGlkZGVuO2Rpc3BsYXk6YmxvY2s7IiBvbm1vdXNlb3Zlcj0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0ndW5kZXJsaW5lJyIgb25tb3VzZW91dD0idGhpcy5zdHlsZS50ZXh0RGVjb3JhdGlvbj0nJyI+w5Z6ZWwgU3BvcmN1bGFyPC90ZD48L3RyPjwvdGFibGU+PC90ZD48L3RyPjwvdGFibGU+PC90ZD48dGQgc3R5bGU9ImJvcmRlcjoxcHggc29saWQgIzQyNDI0Mjt2ZXJ0aWNhbC1hbGlnbjp0b3AiPjx0YWJsZSBzdHlsZT0id2lkdGg6MTAwJSI+PHRyPjx0ZCBvbm1vdXNlb3Zlcj0ic3R5bGUuY3Vyc29yPSdwb2ludGVyJyIgb25tb3VzZW91dD0ic3R5bGUuY3Vyc29yPSdkZWZhdWx0JyIgb25jbGljaz0id2luZG93LmxvY2F0aW9uLmhyZWY9J01pbGxpVGFraW1sYXJCaWxnaS5hc3B4P1Njb3V0S3VsdXBJRD16OVBmVVhERU1mSmN1MmdtRG1wSHdFbDluVldsJTJiYzBueVg0YmpyMmZCMDAlM2QmVGFraW1UaXBLb2R1PXJqRThYaXBQU2V6VkhoYSUyYmhGZmFMZ1NhYjVPRWlNJTJiM0RGRUlRcTJHRjNnJTNkJyI+PHRhYmxlIGNlbGxwYWRkaW5nPSIwIiBjZWxsc3BhY2luZz0iMCIgYWxpZ249ImNlbnRlciI+PHRyPjx0ZCBzdHlsZT0id2lkdGg6OTBweDtoZWlnaHQ6MTAwcHg7dGV4dC1hbGlnbjpjZW50ZXI7YmFja2dyb3VuZC1pbWFnZTp1cmwoSW1hZ2Uvd2hpdGVfYmcucG5nKTtiYWNrZ3JvdW5kLXJlcGVhdDpuby1yZXBlYXQ7YmFja2dyb3VuZC1wb3NpdGlvbjpjZW50ZXIiPjxpbWcgYm9yZGVyPSIwIiBzcmM9IkltYWdlL3RmZjc1LnBuZyIvPjwvdGQ+PC90cj48dHI+PHRkIHN0eWxlPSJ0ZXh0LWFsaWduOmNlbnRlcjt3aWR0aDo5MHB4O292ZXJmbG93OmhpZGRlbjtkaXNwbGF5OmJsb2NrOyIgb25tb3VzZW92ZXI9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249J3VuZGVybGluZSciIG9ubW91c2VvdXQ9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249JyciPjIwMTggS2FybWE8L3RkPjwvdHI+PC90YWJsZT48L3RkPjwvdHI+PC90YWJsZT48L3RkPjx0ZCBzdHlsZT0iYm9yZGVyOjFweCBzb2xpZCAjNDI0MjQyO3ZlcnRpY2FsLWFsaWduOnRvcCI+PHRhYmxlIHN0eWxlPSJ3aWR0aDoxMDAlIj48dHI+PHRkIG9ubW91c2VvdmVyPSJzdHlsZS5jdXJzb3I9J3BvaW50ZXInIiBvbm1vdXNlb3V0PSJzdHlsZS5jdXJzb3I9J2RlZmF1bHQnIiBvbmNsaWNrPSJ3aW5kb3cubG9jYXRpb24uaHJlZj0nTWlsbGlUYWtpbWxhckJpbGdpLmFzcHg/U2NvdXRLdWx1cElEPXdhSGlYUDFZbmhySWNkT3pMU2tDSXUxQ0lxRXluQUhrWnFLS0dCcFlIUlElM2QmVGFraW1UaXBLb2R1PVZXelZ6Ymk0bHZaZE1BcGlsNjl5T3hSJTJieENsVnlqV3Q3N2VydUpxNzZ2NCUzZCciPjx0YWJsZSBjZWxscGFkZGluZz0iMCIgY2VsbHNwYWNpbmc9IjAiIGFsaWduPSJjZW50ZXIiPjx0cj48dGQgc3R5bGU9IndpZHRoOjkwcHg7aGVpZ2h0OjEwMHB4O3RleHQtYWxpZ246Y2VudGVyO2JhY2tncm91bmQtaW1hZ2U6dXJsKEltYWdlL3doaXRlX2JnLnBuZyk7YmFja2dyb3VuZC1yZXBlYXQ6bm8tcmVwZWF0O2JhY2tncm91bmQtcG9zaXRpb246Y2VudGVyIj48aW1nIGJvcmRlcj0iMCIgc3JjPSJJbWFnZS90ZmY3NS5wbmciLz48L3RkPjwvdHI+PHRyPjx0ZCBzdHlsZT0idGV4dC1hbGlnbjpjZW50ZXI7d2lkdGg6OTBweDtvdmVyZmxvdzpoaWRkZW47ZGlzcGxheTpibG9jazsiIG9ubW91c2VvdmVyPSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPSd1bmRlcmxpbmUnIiBvbm1vdXNlb3V0PSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPScnIj4yMDE5IEthcm1hPC90ZD48L3RyPjwvdGFibGU+PC90ZD48L3RyPjwvdGFibGU+PC90ZD48dGQgc3R5bGU9ImJvcmRlcjoxcHggc29saWQgIzQyNDI0Mjt2ZXJ0aWNhbC1hbGlnbjp0b3AiPjx0YWJsZSBzdHlsZT0id2lkdGg6MTAwJSI+PHRyPjx0ZCBvbm1vdXNlb3Zlcj0ic3R5bGUuY3Vyc29yPSdwb2ludGVyJyIgb25tb3VzZW91dD0ic3R5bGUuY3Vyc29yPSdkZWZhdWx0JyIgb25jbGljaz0id2luZG93LmxvY2F0aW9uLmhyZWY9J01pbGxpVGFraW1sYXJCaWxnaS5hc3B4P1Njb3V0S3VsdXBJRD0yUlJaVlZidjZZcFo2YktKSldhd0gwUFBGdXpkekZNOWJCZW1nb09jUVBzJTNkJlRha2ltVGlwS29kdT0ydFU4b3doZ2RxRXJtTDVSbiUyYmxiejBzJTJiSXZCU21nMEdGVWpIdUwzQmxQWSUzZCciPjx0YWJsZSBjZWxscGFkZGluZz0iMCIgY2VsbHNwYWNpbmc9IjAiIGFsaWduPSJjZW50ZXIiPjx0cj48dGQgc3R5bGU9IndpZHRoOjkwcHg7aGVpZ2h0OjEwMHB4O3RleHQtYWxpZ246Y2VudGVyO2JhY2tncm91bmQtaW1hZ2U6dXJsKEltYWdlL3doaXRlX2JnLnBuZyk7YmFja2dyb3VuZC1yZXBlYXQ6bm8tcmVwZWF0O2JhY2tncm91bmQtcG9zaXRpb246Y2VudGVyIj48aW1nIGJvcmRlcj0iMCIgc3JjPSJJbWFnZS90ZmY3NS5wbmciLz48L3RkPjwvdHI+PHRyPjx0ZCBzdHlsZT0idGV4dC1hbGlnbjpjZW50ZXI7d2lkdGg6OTBweDtvdmVyZmxvdzpoaWRkZW47ZGlzcGxheTpibG9jazsiIG9ubW91c2VvdmVyPSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPSd1bmRlcmxpbmUnIiBvbm1vdXNlb3V0PSJ0aGlzLnN0eWxlLnRleHREZWNvcmF0aW9uPScnIj5VMTQgS3Vsw7xwIFNlw6dtZWxlcmk8L3RkPjwvdHI+PC90YWJsZT48L3RkPjwvdHI+PC90YWJsZT48L3RkPjx0ZCBzdHlsZT0iYm9yZGVyOjFweCBzb2xpZCAjNDI0MjQyO3ZlcnRpY2FsLWFsaWduOnRvcCI+PHRhYmxlIHN0eWxlPSJ3aWR0aDoxMDAlIj48dHI+PHRkIG9ubW91c2VvdmVyPSJzdHlsZS5jdXJzb3I9J3BvaW50ZXInIiBvbm1vdXNlb3V0PSJzdHlsZS5jdXJzb3I9J2RlZmF1bHQnIiBvbmNsaWNrPSJ3aW5kb3cubG9jYXRpb24uaHJlZj0nTWlsbGlUYWtpbWxhckJpbGdpLmFzcHg/U2NvdXRLdWx1cElEPXdxRWhjcDR5ZERORVQxV0klMmZhNE5UVzlTRSUyYkx1Z3J6VnhaOGdsdGdrRWlNJTNkJlRha2ltVGlwS29kdT1teXQwUWo3VmwzbFZUVzJ0dlUyV3dQRXh2ZE5nWk1RSE1zT2NGQW1OMTF3JTNkJyI+PHRhYmxlIGNlbGxwYWRkaW5nPSIwIiBjZWxsc3BhY2luZz0iMCIgYWxpZ249ImNlbnRlciI+PHRyPjx0ZCBzdHlsZT0id2lkdGg6OTBweDtoZWlnaHQ6MTAwcHg7dGV4dC1hbGlnbjpjZW50ZXI7YmFja2dyb3VuZC1pbWFnZTp1cmwoSW1hZ2Uvd2hpdGVfYmcucG5nKTtiYWNrZ3JvdW5kLXJlcGVhdDpuby1yZXBlYXQ7YmFja2dyb3VuZC1wb3NpdGlvbjpjZW50ZXIiPjxpbWcgYm9yZGVyPSIwIiBzcmM9IkltYWdlL3RmZjc1LnBuZyIvPjwvdGQ+PC90cj48dHI+PHRkIHN0eWxlPSJ0ZXh0LWFsaWduOmNlbnRlcjt3aWR0aDo5MHB4O292ZXJmbG93OmhpZGRlbjtkaXNwbGF5OmJsb2NrOyIgb25tb3VzZW92ZXI9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249J3VuZGVybGluZSciIG9ubW91c2VvdXQ9InRoaXMuc3R5bGUudGV4dERlY29yYXRpb249JyciPkvEsXpsYXIgVTE1IELDtmxnZSBTZcOnbWVsZXJpPC90ZD48L3RyPjwvdGFibGU+PC90ZD48L3RyPjwvdGFibGU+PC90ZD48L3RhYmxlPmRk4g80DqL4VXo2+XyeZ3FquxcYNm8=" />
</div>

<script type="text/javascript">
//<![CDATA[
var theForm = document.forms['aspnetForm'];
if (!theForm) {
    theForm = document.aspnetForm;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
//]]>
</script>


<script src="/WebResource.axd?d=ew5hI--m9laTXRs0SXs23Fq6IuPfjctwS4Hhch22dThgL3GG7WypAoL8qs-6mDH4vsud1SMQ4vC2BEBp2i-85mzedWE1&amp;t=638901879720898773" type="text/javascript"></script>


<script src="/WebResource.axd?d=9rDFCTOkfGd41u4uoaFH9nMSZEv1D-H-89C8f-8mJtSzfrfvRwZi_cMt-oBAAgY4VC5PDlvHtgzEoayEslWNQP4sEu41&amp;t=638901879720898773" type="text/javascript"></script>
<div>

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="05619B03" />
</div>
        <div>
            <table style="width: 100%" cellpadding="0" cellspacing="0">
                <tr class="trTopMenu">
                    <td colspan="2">
                        <table style="width: 100%; background-image: url(Image/top_bg2.jpg); border-bottom: 2px solid #424242">
                            <tr>
                                <td style="width: 100px; height: 90px">
                                    <a href="Menu.aspx">
                                        <img id="ctl00_imgLogo" src="Image/tff_logo.png" style="width:75px;border-width:0px;" /></a>
                                </td>
                                <td style="text-align: left; color: white; vertical-align: middle; font-size: 26px; font-weight: bold">Türkiye Futbol Federasyonu
                                    <br />
                                    <span style="color: silver; font-size: 18px">Video Analiz ve Gözlem</span>
                                </td>
                                <td>
                                    <table style="width: 100%; text-align: right">
                                        <tr>
                                            <td>&nbsp;
                                            </td>
                                            <td style="width: 200px; text-align: center">
                                                <img id="ctl00_imgUserPhoto" onclick="clik_lblUserName()" onError="this.src=&#39;Image/Default.png&#39;" src="/Pages/Scout/Image/UserPhoto/2583.jpg?v=2200" style="border-color:White;border-width:1px;border-style:Solid;height:45px;width:35px;cursor:pointer" />
                                            </td>
                                            <td style="width: 120px">
                                                <input type="submit" name="ctl00$lnkCikis" value="Oturumu Kapat" onclick="if (!(confirm(&#39;Oturumu kapatmak istediðinizden emin misiniz?&#39;))) return false;" id="ctl00_lnkCikis" class="scoutLinkButtonSmall" /></td>
                                        </tr>
                                        <tr>
                                            <td>&nbsp;
                                            </td>
                                            <td style="width: 200px; text-align: center">
                                                <a id="ctl00_lblUserName" href="javascript:__doPostBack(&#39;ctl00$lblUserName&#39;,&#39;&#39;)" style="white-space: nowrap; vertical-align: bottom">STAJ STAJ</a></td>
                                            <td style="color: white; font-size: 12px; text-align: right; vertical-align: bottom">TFF Teknoloji</td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>

                        <table cellpadding="0" cellspacing="0" style="width: 100%;">
                            <tr>
                                <td style="vertical-align: top; padding-top: 3px; width: 150px;" class="tdMenu">
                                    <table cellspacing="0">
                                        
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl00$btnMenu" value="Milli Takýmlar" onclick="window.location=&#39;../../Pages/Scout/MilliTakimlar.aspx&#39;;return false;" id="ctl00_Menu_ctl00_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#d70d16" style="color:#D70D16;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl01$btnMenu" value="Futbolcularým" onclick="window.location=&#39;../../Pages/Scout/Futbolcularim.aspx&#39;;return false;" id="ctl00_Menu_ctl01_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl02$btnMenu" value="Ýstatistikler" onclick="window.location=&#39;../../Pages/Scout/Istatistikler.aspx&#39;;return false;" id="ctl00_Menu_ctl02_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl03$btnMenu" value="Popüler Oyuncular" onclick="window.location=&#39;../../Pages/Scout/PopulerOyuncular.aspx&#39;;return false;" id="ctl00_Menu_ctl03_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl04$btnMenu" value="Kulüpler" onclick="window.location=&#39;../../Pages/Scout/Ligler.aspx&#39;;return false;" id="ctl00_Menu_ctl04_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl05$btnMenu" value="Karmalar" onclick="window.location=&#39;../../Pages/Scout/Karmalar.aspx&#39;;return false;" id="ctl00_Menu_ctl05_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl06$btnMenu" value="Rakipler" onclick="window.location=&#39;../../Pages/Scout/Rakipler.aspx&#39;;return false;" id="ctl00_Menu_ctl06_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl07$btnMenu" value="Antropometrik Ölçümler" onclick="window.location=&#39;../../Pages/Scout/Olcumler.aspx&#39;;return false;" id="ctl00_Menu_ctl07_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl08$btnMenu" value="Oyuncu Raporlarý" onclick="window.location=&#39;../../Pages/Scout/Raporlar.aspx&#39;;return false;" id="ctl00_Menu_ctl08_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl09$btnMenu" value="Dünya Kupasý 26" onclick="window.location=&#39;../../Pages/Scout/Wc26.aspx&#39;;return false;" id="ctl00_Menu_ctl09_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl10$btnMenu" value="Güncel Videolar" onclick="window.location=&#39;../../Pages/Scout/GenelVideo.aspx&#39;;return false;" id="ctl00_Menu_ctl10_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl11$btnMenu" value="Scout Profilleri" onclick="window.location=&#39;../../Pages/Scout/Scoutlar.aspx&#39;;return false;" id="ctl00_Menu_ctl11_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl12$btnMenu" value="Yetenek Baþvurular" onclick="window.location=&#39;../../Pages/Scout/RaporlarYetenek.aspx&#39;;return false;" id="ctl00_Menu_ctl12_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl13$btnMenu" value="Doküman Yönetimi" onclick="window.location=&#39;../../Pages/Scout/DYS.aspx&#39;;return false;" id="ctl00_Menu_ctl13_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl14$btnMenu" value="Rehber" onclick="window.location=&#39;../../Pages/Scout/Rehber.aspx&#39;;return false;" id="ctl00_Menu_ctl14_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl15$btnMenu" value="Esame Raporu" onclick="window.location=&#39;../../Pages/Scout/OyuncununOynadigiMaclar.aspx&#39;;return false;" id="ctl00_Menu_ctl15_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl16$btnMenu" value="Mesajlar" onclick="window.location=&#39;../../Pages/Scout/Mesajlar.aspx&#39;;return false;" id="ctl00_Menu_ctl16_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl17$btnMenu" value="Antrenman Planlarý" onclick="window.location=&#39;../../Pages/Scout/AntrenmanTakvimi.aspx&#39;;return false;" id="ctl00_Menu_ctl17_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl18$btnMenu" value="Antrenmanlar" onclick="window.location=&#39;../../Pages/Scout/Antrenmanlar.aspx&#39;;return false;" id="ctl00_Menu_ctl18_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl19$btnMenu" value="Kulüp Geliþim" onclick="window.location=&#39;../../Pages/Scout/KulupOyunculari.aspx&#39;;return false;" id="ctl00_Menu_ctl19_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl20$btnMenu" value="Geliþim Ligi Raporlarý" onclick="window.location=&#39;../../Pages/Scout/GelisimLigiRaporlari.aspx&#39;;return false;" id="ctl00_Menu_ctl20_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl21$btnMenu" value="Þifre Deðiþtirme" onclick="window.location=&#39;../../Pages/Scout/SifreDegistirme.aspx&#39;;return false;" id="ctl00_Menu_ctl21_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl22$btnMenu" value="Oyuncu Eþleþtirme" onclick="window.location=&#39;../../Pages/Scout/OptaOyuncuEslestirme.aspx&#39;;return false;" id="ctl00_Menu_ctl22_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl23$btnMenu" value="Analiz Departmaný" onclick="window.location=&#39;../../Pages/Scout/AnalizDepartmani.aspx&#39;;return false;" id="ctl00_Menu_ctl23_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl24$btnMenu" value="Performans Testleri" onclick="window.location=&#39;../../Pages/Scout/Testler.aspx&#39;;return false;" id="ctl00_Menu_ctl24_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl25$btnMenu" value="Teknik Testler" onclick="window.location=&#39;../../Pages/Scout/TeknikTestler.aspx&#39;;return false;" id="ctl00_Menu_ctl25_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl26$btnMenu" value="Sakatlýklar" onclick="window.location=&#39;../../Pages/Scout/Sakatliklar.aspx&#39;;return false;" id="ctl00_Menu_ctl26_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl27$btnMenu" value="Maç Raporlarý" onclick="window.location=&#39;../../Pages/Scout/MacRaporlari.aspx&#39;;return false;" id="ctl00_Menu_ctl27_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl28$btnMenu" value="Ýzleyici Atama" onclick="window.location=&#39;../../Pages/Scout/MacAtama.aspx&#39;;return false;" id="ctl00_Menu_ctl28_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                                <tr>
                                                    <td>
                                                        <input type="submit" name="ctl00$Menu$ctl29$btnMenu" value="Kullanýcý Yönetimi" onclick="window.location=&#39;../../Pages/Scout/KullaniciSorgulama.aspx&#39;;return false;" id="ctl00_Menu_ctl29_btnMenu" class="scoutLinkButtonBig" onmouseover="style.color=&#39;white&#39;;style.cursor=&#39;pointer&#39;" onmouseout="style.color=this.getAttribute(&#39;DefaultColor&#39;);style.cursor=&#39;default&#39;" DefaultColor="#8f8f8f" style="color:#8F8F8F;" />
                                                    </td>
                                                </tr>
                                            
                                    </table>
                                </td>
                                <td style="vertical-align: top">

                                    <table cellpadding="0" cellspacing="0" width="100%">
                                        <tr>
                                            <td>&nbsp;
                                                <table id="ctl00_tblFutbolcuAra" cellpadding="3" cellspacing="0" align="center">
	<tr>
		<td style="font-size: 12px; color: silver">Futbolcu Ara
                                                        </td>
		<td>
                                                            <input name="ctl00$txtFutbolcuArama" type="text" id="ctl00_txtFutbolcuArama" class="inputs" style="background-color:Silver;font-size:12px;" />
                                                            <input type="hidden" name="ctl00$hdnFutbolcuArama" id="ctl00_hdnFutbolcuArama" />
                                                        </td>
		<td>
                                                            <input type="submit" name="ctl00$btnAra" value="Ara" id="ctl00_btnAra" style="font-size:12px;" />
                                                        </td>
	</tr>
</table>

                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <div id="ctl00_divLink">&nbsp;&nbsp;&nbsp;<a href="MilliTakimlar.aspx">&nbsp;Milli Takýmlar&nbsp;</a><span style="color:#d70d16;font-weight:bold">&nbsp;&gt;&nbsp;</span></div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                
<div id="ctl00_ContentPlaceHolder1_divGallerie"><table cellpadding="10" cellspacing="10"><tr><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=j0GriV27Aga8LBZPTVfHukSnyRyagCzuDrtrvhz15v8%3d&TakimTipKodu=DH%2fVTKGwYm55QrnCfvfjqbFNkRemUPoEU%2b9URKnxxsQ%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">A Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=8gTOovVZn0cDtONoAvFgQ6IA47u6YhPd8sZHVWnu2TU%3d&TakimTipKodu=W%2fpEAglWgzqXvOtQFIThm%2fE%2bgyiPwT5%2fCptB97eFVy0%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">A2 Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=te%2b9wv7JUYKPuIb%2fH9ghZCIGvvWBCo7FP%2f06u6fbIzg%3d&TakimTipKodu=%2fyDWzVnIi%2fzqIEJtbjYJqFo2Ze%2bKCqIrojnHnjejyiE%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">U21 Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=DbOQ6JE1m%2fzHKSsEgk5QNVO6IvONWjfk07J057xD6pk%3d&TakimTipKodu=mzk68qGuQT6z89WqQKQSf9N9BdmTekQpGPG2e0%2fX4yU%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">U20 Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=WjyDnnuZPethA%2f%2bKlL1U5dBztkrkAnobhSyhwaNtZyg%3d&TakimTipKodu=c%2fCinesSlz3qx5VEvWqe38LlTv%2fYAqXYrJlHC%2bfeiTk%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">U19 Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=agWAE1BfJBg12nfffl3dRUvrn06b9ahpR0zkNq%2fm1kk%3d&TakimTipKodu=9WIl%2f%2f9W3fPeyVMpZEt0r%2bN9lHl2GEKQBLAYpHxoqj8%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">U18 Milli</td></tr></table></td></tr></table></td></tr><tr><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=r7cUZ%2bWCoXalHGukZHJC9FaKRIF4Pi7kOGS3zNac6xQ%3d&TakimTipKodu=2wesKp0gqIQUd8HtnwkLsFU9MnPaiJs9Fob%2fGGGQDP8%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">U17 Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=FcUBfqCbfj%2bjVtH6eaaunaL0pdYZ%2bxVVFDA8UzGlSCA%3d&TakimTipKodu=MmmS8IH9L21xqdGK5Tz4C1AwmHC6JVfthTe1NOvcB3M%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">U16 Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=lq6CMfF%2b2MnBXsQzd7sE8qFpltmyxujyCIjGUweepUQ%3d&TakimTipKodu=04fKhLCL%2bdWftS%2b5GBPCaKZSrLwDg25cwyjpRXbFv7I%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">U15 Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=fCRJz0BI%2fkcO4z7v74KnutPvfC%2fRHGRtPeGv0zg9bxA%3d&TakimTipKodu=8omzhWRTcitWF%2fli3BjRf%2fx9FQ%2fbInMUDur%2fWaHb6IQ%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">U14 Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=8omzhWRTcitWF%2fli3BjRf%2fx9FQ%2fbInMUDur%2fWaHb6IQ%3d&TakimTipKodu=%2fmhABJAlwxyULytcmIJqhetvODWaKUyEm8L9CiAZRJA%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">Kadýnlar A Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=9rjSLaznyWDmWHpZjYe0GvsXz%2bjk5iXz2zpt6GmRAKU%3d&TakimTipKodu=PmV1h5v7Gbsj3M7YX5YTVaLtWd3BAggjLXVweNFyOJo%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">Kadýnlar U23 Milli</td></tr></table></td></tr></table></td></tr><tr><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=04fKhLCL%2bdWftS%2b5GBPCaKZSrLwDg25cwyjpRXbFv7I%3d&TakimTipKodu=hw8DULWWUsi7NXqugjmGpLDUXI3xrEknb3XGLnGrEoU%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">Kadýnlar U19 Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=Lul12pj5YRCKvjgU44IU3MNJmusrybiEndiAJjzSqSs%3d&TakimTipKodu=1ZkwlAtjho9YIxg3%2baxmmIFlzi2aZk%2blUuhXIza3%2b2Y%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">Kýzlar U18 Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=MmmS8IH9L21xqdGK5Tz4C1AwmHC6JVfthTe1NOvcB3M%3d&TakimTipKodu=Tjeqq2gW2%2fkNqJ8Xy80mBoQtxNm%2f1bkoU8aXWolrza4%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">Kýzlar U17 Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=2wesKp0gqIQUd8HtnwkLsFU9MnPaiJs9Fob%2fGGGQDP8%3d&TakimTipKodu=DmxJCRv%2bhya%2f7M%2b7YzcyxfWbni1XGq3bJ4DtwEm%2b02I%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">Kýzlar U15 Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=9WIl%2f%2f9W3fPeyVMpZEt0r%2bN9lHl2GEKQBLAYpHxoqj8%3d&TakimTipKodu=KGWo9%2fG8JsP7fVhMPwQJ%2fYXHJgzyxMpLErwUECctUq4%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">Futsal Milli</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=c%2fCinesSlz3qx5VEvWqe38LlTv%2fYAqXYrJlHC%2bfeiTk%3d&TakimTipKodu=P5Y7Zul7LrjCvFyG8usIui1afIQt1wL5jcbOoIMW6qQ%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">Plaj Milli</td></tr></table></td></tr></table></td></tr><tr><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=XbKBvjO0lE5Vzzt7GDOPYz1M7rvS1EOQ1JK4TzbhPzc%3d&TakimTipKodu=629du%2ffMz3C8k%2bOP5rDp4GzqXAVAxcYCGHrlJVrdSFs%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">Özel Sporcular</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=z9PfUXDEMfJcu2gmDmpHwEl9nVWl%2bc0nyX4bjr2fB00%3d&TakimTipKodu=rjE8XipPSezVHha%2bhFfaLgSab5OEiM%2b3DFEIQq2GF3g%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">2018 Karma</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=waHiXP1YnhrIcdOzLSkCIu1CIqEynAHkZqKKGBpYHRQ%3d&TakimTipKodu=VWzVzbi4lvZdMApil69yOxR%2bxClVyjWt77eruJq76v4%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">2019 Karma</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=2RRZVVbv6YpZ6bKJJWawH0PPFuzdzFM9bBemgoOcQPs%3d&TakimTipKodu=2tU8owhgdqErmL5Rn%2blbz0s%2bIvBSmg0GFUjHuL3BlPY%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">U14 Kulüp Seçmeleri</td></tr></table></td></tr></table></td><td style="border:1px solid #424242;vertical-align:top"><table style="width:100%"><tr><td onmouseover="style.cursor='pointer'" onmouseout="style.cursor='default'" onclick="window.location.href='MilliTakimlarBilgi.aspx?ScoutKulupID=wqEhcp4ydDNET1WI%2fa4NTW9SE%2bLugrzVxZ8gltgkEiM%3d&TakimTipKodu=myt0Qj7Vl3lVTW2tvU2WwPExvdNgZMQHMsOcFAmN11w%3d'"><table cellpadding="0" cellspacing="0" align="center"><tr><td style="width:90px;height:100px;text-align:center;background-image:url(Image/white_bg.png);background-repeat:no-repeat;background-position:center"><img border="0" src="Image/tff75.png"/></td></tr><tr><td style="text-align:center;width:90px;overflow:hidden;display:block;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration=''">Kýzlar U15 Bölge Seçmeleri</td></tr></table></td></tr></table></td></table></div>


                                            </td>
                                        </tr>
                                    </table>

                                </td>
                            </tr>
                        </table>

                    </td>
                </tr>
            </table>
        </div>
        <script>
            $(document).ready(function() 
            {    
                $("input#ctl00_txtFutbolcuArama").autocomplete({  source: function(request, response) {
                        
                        $.ajax({
                            url: "../ExternalCallBackPages/Futbolcu.aspx",
                            type: "GET",
                            data: {
                               q: request.term
                            },
                            success: function( item ) {
                                    var rows = autocompleteJSONParseCode(item);
                                    response(rows.slice(0, 100));
                              }
                            });
                          },
                          minLength: 3,
                          select:function (event, ui) {
                                if (!ui.item.value) {$("#ctl00_hdnFutbolcuArama").val("");return;}
                                $("#ctl00_hdnFutbolcuArama").val(ui.item.futbolcuID.toString());
                          }
                          
                });
                
            });
        </script>
    

<script type="text/javascript">
//<![CDATA[
WebForm_AutoFocus('btnAra');//]]>
</script>
</form>
</body>
</html>
